/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/species/esc_v4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get look-up for  ESC V4 tree species
         * @description Returns look-up (flat array) of species codes, common names and scientific names of species used in ESC V4.
         */
        get: operations["get_esc_v4_species_api_species_esc_v4_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/app4future": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get look-up for APP4Future tree species
         * @description Returns look-up (flat array) of species codes, common names and scientific names of species used in APP4Future.
         */
        get: operations["get_app4future_species_api_species_app4future_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/indicator_species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of indicator species
         * @description Returns a list of indicator species for use in vegetation survey to determine SMR and SNR. Intended for use in drop-down for vegetation survey.
         */
        get: operations["get_indicator_species_api_soil_indicator_species_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of soil types
         * @description Returns list of soil types to be used in soil type survey to determine SMR and SNR. Intended for use in drop-down for soil survey.
         */
        get: operations["get_soil_types_api_soil_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get look-up for mapping numerical SMR and SNR values to categorical
         * @description Returns look-up (flat array) for SMR and SNR. Intended to be used to map numerical SMR and SNR values (e.g. those from from api/soil/extract_values) to categorical values.
         */
        get: operations["get_soil_mapping_api_soil_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/vegetation_survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run vegetation survey to determine soil values
         * @description Calculates soil values (SMR, SNR, F, RN and Wilson) from indicator plants and their corresponding abundances. Percentage abundance as an integer (e.g., 30% -> 30). Values do not need to sum to 100%.
         */
        post: operations["vegetation_survey_api_soil_vegetation_survey_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/extract_values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract soil values from national map
         * @description Extracts SMR and SNR (numerical values) for specified location. Values are extracted from 250m SMR and SNR raster dataset.
         */
        post: operations["extract_soil_values_api_soil_extract_values_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/soil/type_survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run soil type survey to determine soil values
         * @description Calculates SMR and SNR from soil type. Returns numerical SMR and SNR values.
         */
        post: operations["soil_survey_api_soil_type_survey_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/climate/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get list of available climate datasets for location
         * @description Returns a list of available climate datasets for the specified location, along with corresponding available RCPs and time periods
         */
        post: operations["get_available_climate_datasets_api_climate_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/climate/extract_values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract climate variable values
         * @description Extracts specified climate variable values for multiple climate scenario for specified location.
         *                         Location co-ordinates must be provided in EPSG:27700.
         *                         The available climate datasets for your location and their corresponding RCP, time period and climate variable options can be viewed using POST api/climate/datasets.
         *                         The response object has the following structure:
         *                         - inputs: Input configuration used
         *                         - results: Nested dictionary of scenario outputs accessed using results[period][rcp]-> response
         */
        post: operations["extract_climate_values_api_climate_extract_values_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topographic/extract_values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract topographic values
         * @description Extracts topographic values (elevation, slope, aspect and DAMS) at specified location. Currently takes a while as extracting from 50m raster data.
         */
        post: operations["extract_topographic_values_api_topographic_extract_values_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/esc_v4/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get options for  ESC V4 model run
         * @description Returns options for running ESC V4, including species, filters, site management and site modification options. Intended for use in drop-downs.
         */
        get: operations["get_esc_v4_options_api_models_esc_v4_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/esc_v4/stand/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run ESC V4 model at stand level
         * @description ***Runs ESC V4 model at specified location for multiple climate scenarios and species.***
         *
         *     The response includes scores for each ESC variable, along with overall suitability score, yield class and limiting factor for each species and scenario.
         *
         *     Location co-ordinates must be provided in EPSG:27700.
         *
         *     The response object has the following structure:
         *     - inputs: Input configuration used to run model
         *     - results: Nested dictionary of species outputs. Access using: results[period][rcp][species] -> SpeciesResponse
         */
        post: operations["run_stand_model_api_models_esc_v4_stand_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/app4future/stand/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run APP4Future ESC model at stand level
         * @description ***Runs ESC model (developed for APP4Future, 2025) for a specified location across multiple climate scenarios and species.***
         *
         *     The model uses default SMR and SNR based on the provided location. If SMR and SNR values are supplied in the request (using "soil" parameter) they will override the default values.
         *
         *     The time periods available are 1980_2000, 2000_2020, 2020_2040, 2040_2060 and 2060_2080.
         *     The RCPs available are rcp26, rcp45, rcp60 and rcp85.
         *
         *     The endpoint is set up for running multiple climate scenarios (as shown in example request body).
         *     A single scenario can also be run. For example, a baseline scenario using "period_list": ["1980_2000"] and "rcp_list": ["baseline"], or for a future scenario using ("period_list": ["2060_2080"] and "rcp_list": ["rcp85"].
         *
         *     climate_dataset = "CHESS_SCAPE_v2" should be used (currently the only climate dataset available for this model).
         *
         *     The response object has the following structure:
         *     • inputs: Input configuration used to run model
         *     • results: Nested dictionary of species outputs. A species results can be accessed using results[period][rcp][species] e.g. results["2060_2080"]["rcp85"]["ASP"]
         *
         *     The response includes variables scores for each species and climate scenario.
         *     All scores range from 0-1, except for species where SMR, SNR, or DAMS responses are unknown; in those cases the value is –1.0.
         *
         *     The variable scores are:
         *     - *prF*: annual precipitation in mm (0: Unsuitable, 1: Suitable)
         *     - *atF*: accumulated temperature in C (0: Unsuitable, 1: Suitable)
         *     - *wq_aridityF*: warmest quarter aridity in mm/C (0: Unsuitable, 1: Suitable)
         *     - *smrF*: Soil moisture regime (SMR) (0-0.3: Unsuitable, 0.3-0.5: Marginal, 0.5-0.75: Suitable, 0.75-1: Very suitable)
         *     - *snrF*: Soil nutrient regime (SNR) (0-0.3: Unsuitable, 0.3-0.5: Marginal, 0.5-0.75: Suitable, 0.75-1: Very suitable)
         *     -  *daF*: DAMS response (exposure) (0-0.3: Unsuitable, 0.3-0.5: Marginal, 0.5-0.75: Suitable, 0.75-1: Very suitable)
         *
         *     Species codes can be mapped to names using api/species/app4future. SMR and SNR values can be mapped their more informative names using api/soil/mappings.
         */
        post: operations["run_stand_model_agro_api_models_app4future_stand_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/nvc_v4/stand/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run NVC model at stand level */
        post: operations["run_nvc_model_api_models_nvc_v4_stand_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/fdt_v4/stand/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run FDT model at stand level */
        post: operations["run_fdt_model_api_models_fdt_v4_stand_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/hmss/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run hylobius management system model
         * @description Returns input configuration, HMSS model results and management results
         */
        post: operations["run_model_api_models_hmss_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/results_glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get content to populate glossary for result tables
         * @description Get content to populate glossary for result tables
         */
        get: operations["get_result_glossary_api_content_results_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** A4FSpeciesResponse */
        A4FSpeciesResponse: {
            /**
             * Prf
             * @description Response score for annual precipitation (0-1)
             */
            prF: number | null;
            /**
             * Atf
             * @description Response score for accummulated temperature (0-1)
             */
            atF: number | null;
            /**
             * Wq Aridityf
             * @description Response score for warmest quarter aridity (0-1)
             */
            wq_aridityF: number | null;
            /**
             * Smrf
             * @description Response score for SMR (0-1)
             */
            smrF: number | null;
            /**
             * Snrf
             * @description Response score for SNR (0-1)
             */
            snrF: number | null;
            /**
             * Daf
             * @description Response value for DAMS (exposure) (0-1)
             */
            daF: number | null;
        };
        /** APP4FutureInput */
        APP4FutureInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
            /**
             * Climate Dataset
             * @example CHESS_SCAPE_v2
             */
            climate_dataset: string;
            /**
             * Period List
             * @description List of climate periods (should correspond to list of RCPs)
             * @example [
             *       "1980_2000",
             *       "2040_2060",
             *       "2060_2080",
             *       "2040_2060",
             *       "2060_2080"
             *     ]
             */
            period_list: ("1980_2000" | "2000_2020" | "2020_2040" | "2040_2060" | "2060_2080")[];
            /**
             * Rcp List
             * @description List of RCPs (should correspond to list of periods)
             * @example [
             *       "baseline",
             *       "rcp26",
             *       "rcp26",
             *       "rcp85",
             *       "rcp85"
             *     ]
             */
            rcp_list: ("baseline" | "rcp26" | "rcp45" | "rcp60" | "rcp85")[];
            /**
             * Soil
             * @example {
             *       "smr": 3,
             *       "snr": 5
             *     }
             */
            soil?: {
                [key: string]: number;
            } | null;
        };
        /** APP4FutureResponse */
        APP4FutureResponse: {
            inputs: components["schemas"]["APP4FutureInput"];
            /** Results */
            results: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: components["schemas"]["A4FSpeciesResponse"];
                    };
                };
            };
        };
        /** ClimateDatasetsInput */
        ClimateDatasetsInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
        };
        /** ClimateDatasetsResponse */
        ClimateDatasetsResponse: {
            /** Name */
            name: string;
            /** Coverage */
            coverage: string;
            /** Description */
            description: string;
            /** Variables */
            variables: string[];
            /** Scenarios */
            scenarios?: string[] | null;
            /** Rcps */
            rcps?: string[] | null;
            /** Members */
            members?: string[] | null;
        };
        /** ClimateExtractValuesInput */
        ClimateExtractValuesInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
            /**
             * Climate Dataset
             * @example CHESS_SCAPE_v1
             */
            climate_dataset: string;
            /**
             * Variables
             * @example [
             *       "at",
             *       "md",
             *       "ct",
             *       "dams"
             *     ]
             */
            variables: ("at" | "md" | "ct" | "dams" | "pr" | "wq_aridity" | "pr_annual" | "pr_winter" | "pr_summer" | "tas")[];
            /**
             * Period List
             * @description List of climate periods (should correspond to list of RCPs)
             * @example [
             *       "1980_2000",
             *       "2060_2080",
             *       "2060_2080"
             *     ]
             */
            period_list: ("1991-2020" | "1980_2000" | "2000_2020" | "2020_2040" | "2040_2060" | "2060_2080")[];
            /**
             * Rcp List
             * @description List of RCPs (should correspond to list of periods)
             * @example [
             *       "baseline",
             *       "rcp26",
             *       "rcp85"
             *     ]
             */
            rcp_list: ("baseline" | "rcp26" | "rcp45" | "rcp60" | "rcp85")[];
        };
        /** ClimateExtractValuesResponse */
        ClimateExtractValuesResponse: {
            inputs: components["schemas"]["ClimateExtractValuesInput"];
            /** Results */
            results: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** ESCV4RunInput */
        ESCV4RunInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
            /**
             * Climate Dataset
             * @example CHESS_SCAPE_v1
             */
            climate_dataset: string;
            /**
             * Period List
             * @description List of climate periods (should correspond to list of RCPs)
             * @example [
             *       "1980_2000",
             *       "2060_2080",
             *       "2060_2080"
             *     ]
             */
            period_list: ("1980_2000" | "2000_2020" | "2020_2040" | "2040_2060" | "2060_2080")[];
            /**
             * Rcp List
             * @description List of RCPs (should correspond to list of periods)
             * @example [
             *       "baseline",
             *       "rcp26",
             *       "rcp85"
             *     ]
             */
            rcp_list: ("baseline" | "rcp26" | "rcp45" | "rcp60" | "rcp85")[];
            /**
             * Smr
             * @example 3
             */
            smr: number;
            /**
             * Snr
             * @example 2
             */
            snr: number;
            /**
             * Smr Source
             * @example Manual entry
             * @enum {string}
             */
            smr_source: "Manual entry" | "Vegetation survey" | "Soil survey" | "National dataset";
            /**
             * Snr Source
             * @example Manual entry
             * @enum {string}
             */
            snr_source: "Manual entry" | "Vegetation survey" | "Soil survey" | "National dataset";
            /**
             * Filterwane
             * @example None
             * @enum {string}
             */
            filterWANE: "None" | "Exempt" | "Not exempt";
            /**
             * Filterconifer
             * @example Conifer
             * @enum {string}
             */
            filterConifer: "None" | "Conifer" | "Broadleaf";
            /**
             * Filternative
             * @example None
             * @enum {string}
             */
            filterNative: "None" | "Yes" | "No";
            /**
             * Filtermain
             * @example Yes
             * @enum {string}
             */
            filterMain: "None" | "Yes" | "No";
            /**
             * Filteragro
             * @example None
             * @enum {string}
             */
            filterAgro: "None" | "Yes" | "No";
            /**
             * Brash
             * @example None (new planting)
             * @enum {string}
             */
            brash: "None (new planting)" | "Fresh brash < 18 months" | " Brash > 18 months";
            /**
             * Drainage
             * @example None
             * @enum {string}
             */
            drainage: "None" | "Drainage installed";
            /**
             * Fertiliser
             * @example None
             * @enum {string}
             */
            fertiliser: "None" | "Fertiliser" | "Nursing mix";
            /**
             * Exposure
             * @example None
             * @enum {string}
             */
            exposure: "None" | "Exposed ridge/Coastal zone" | "Local shelter/Less exposed/Underplanting";
        };
        /** ESCV4RunResponse */
        ESCV4RunResponse: {
            inputs: components["schemas"]["ESCV4RunInput"];
            /** Results */
            results: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: components["schemas"]["ESCV4SpeciesResponse"];
                    };
                };
            };
        };
        /** ESCV4SpeciesResponse */
        ESCV4SpeciesResponse: {
            /**
             * Atf
             * @description Response score for accummulated temperature (0-1)
             */
            atF: number;
            /**
             * Ctf
             * @description Response score for continentality (0-1)
             */
            ctF: number;
            /**
             * Smrf
             * @description Response score for SMR (0-1)
             */
            smrF: number;
            /**
             * Snrf
             * @description Response score for SNR (0-1)
             */
            snrF: number;
            /**
             * Daf
             * @description Response value for DAMS (exposure) (0-1)
             */
            daF: number;
            /**
             * Mdf
             * @description Response value for moisture deficit (0-1)
             */
            mdF: number;
            /**
             * Min Response
             * @description Minimum response value (0-1)
             */
            min_response: number;
            /**
             * Suit
             * @description Timber suitability score (0-1)
             */
            suit: number;
            /**
             * Eco Suit
             * @description Ecological suitability score (0-1)
             */
            eco_suit: number;
            /**
             * Yc
             * @description Yield class (calculated by multiplying species maximum yield class by the suitability score)
             */
            yc: number;
            /**
             * Lim Fac
             * @description Limiting factor (the site variable with minimum response value)
             */
            lim_fac: string;
        };
        /** FDTV4Input */
        FDTV4Input: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
            /**
             * Climate Dataset
             * @example CHESS_SCAPE_v1
             */
            climate_dataset: string;
            /**
             * Period List
             * @description List of climate periods (should correspond to list of RCPs)
             * @example [
             *       "1980_2000",
             *       "2060_2080",
             *       "2060_2080"
             *     ]
             */
            period_list: ("1980_2000" | "2000_2020" | "2020_2040" | "2040_2060" | "2060_2080")[];
            /**
             * Rcp List
             * @description List of RCPs (should correspond to list of periods)
             * @example [
             *       "baseline",
             *       "rcp26",
             *       "rcp85"
             *     ]
             */
            rcp_list: ("baseline" | "rcp26" | "rcp45" | "rcp60" | "rcp85")[];
            /**
             * Smr
             * @example 3
             */
            smr: number;
            /**
             * Snr
             * @example 2
             */
            snr: number;
        };
        /** HMSSModelInput */
        HMSSModelInput: {
            /**
             * Site Id
             * @description Site name or ID
             * @example A1
             */
            site_id: string;
            /**
             * Grid Reference
             * @description Site grid reference
             * @example NN 75501 05738
             */
            grid_reference: string;
            /**
             * Monitoring Year
             * @description Monitoring year (int)
             * @example 2025
             */
            monitoring_year: number;
            /**
             * Felling Month
             * @description Felling month (int)
             * @example 1
             */
            felling_month: number;
            /**
             * Felling Year
             * @description Felling year (int)
             * @example 2023
             */
            felling_year: number;
            /**
             * Planting Year
             * @description Monitoring year (int)
             * @example 2025
             */
            planting_year: number;
            /**
             * Previous Species
             * @example SS
             */
            previous_species: string;
            /**
             * Billet Count
             * @description Total billet count
             * @example 234
             */
            billet_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MappingItem */
        MappingItem: {
            /** Num */
            num: number;
            /** Description */
            description: string;
            /** Code */
            code: string;
        };
        /** ModelsESCV4OptionsResponse */
        ModelsESCV4OptionsResponse: {
            /** Species Filters */
            species_filters: {
                [key: string]: unknown;
            };
            /** Site Management */
            site_management: {
                [key: string]: unknown;
            };
            /** Site Modification */
            site_modification: {
                [key: string]: unknown;
            };
        };
        /** NVCInput */
        NVCInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
            /**
             * Climate Dataset
             * @example CHESS_SCAPE_v1
             */
            climate_dataset: string;
            /**
             * Period List
             * @description List of climate periods (should correspond to list of RCPs)
             * @example [
             *       "1980_2000",
             *       "2060_2080",
             *       "2060_2080"
             *     ]
             */
            period_list: ("1980_2000" | "2000_2020" | "2020_2040" | "2040_2060" | "2060_2080")[];
            /**
             * Rcp List
             * @description List of RCPs (should correspond to list of periods)
             * @example [
             *       "baseline",
             *       "rcp26",
             *       "rcp85"
             *     ]
             */
            rcp_list: ("baseline" | "rcp26" | "rcp45" | "rcp60" | "rcp85")[];
            /**
             * Smr
             * @example 3
             */
            smr: number;
            /**
             * Snr
             * @example 2
             */
            snr: number;
            /**
             * Smr Source
             * @example Manual entry
             * @enum {string}
             */
            smr_source: "Manual entry" | "Vegetation survey" | "Soil survey" | "National dataset";
            /**
             * Snr Source
             * @example Manual entry
             * @enum {string}
             */
            snr_source: "Manual entry" | "Vegetation survey" | "Soil survey" | "National dataset";
            /**
             * Filterwane
             * @example None
             * @enum {string}
             */
            filterWANE: "None" | "Exempt" | "Not exempt";
            /**
             * Filterconifer
             * @example Conifer
             * @enum {string}
             */
            filterConifer: "None" | "Conifer" | "Broadleaf";
            /**
             * Filternative
             * @example None
             * @enum {string}
             */
            filterNative: "None" | "Yes" | "No";
            /**
             * Filtermain
             * @example Yes
             * @enum {string}
             */
            filterMain: "None" | "Yes" | "No";
            /**
             * Filteragro
             * @example None
             * @enum {string}
             */
            filterAgro: "None" | "Yes" | "No";
            /**
             * Brash
             * @example None (new planting)
             * @enum {string}
             */
            brash: "None (new planting)" | "Fresh brash < 18 months" | " Brash > 18 months";
            /**
             * Drainage
             * @example None
             * @enum {string}
             */
            drainage: "None" | "Drainage installed";
            /**
             * Fertiliser
             * @example None
             * @enum {string}
             */
            fertiliser: "None" | "Fertiliser" | "Nursing mix";
            /**
             * Exposure
             * @example None
             * @enum {string}
             */
            exposure: "None" | "Exposed ridge/Coastal zone" | "Local shelter/Less exposed/Underplanting";
        };
        /** NVCSuitability */
        NVCSuitability: {
            /** Atf */
            atF: number;
            /** Ctf */
            ctF: number;
            /** Smrf */
            smrF: number;
            /** Snrf */
            snrF: number;
            /** Daf */
            daF: number;
            /** Mdf */
            mdF: number;
            /** Min Response */
            min_response: number;
            /** Suit */
            suit: number;
            /** Lim Fac */
            lim_fac: string;
        };
        /** NVCV4Response */
        NVCV4Response: {
            inputs: components["schemas"]["NVCInput"];
            /** Results */
            results: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: {
                            [key: string]: components["schemas"]["NVCSuitability"];
                        };
                    };
                };
            };
        };
        /** ResultsGlossary */
        ResultsGlossary: {
            /** Site Information */
            site_information: unknown[];
            /** Species Results */
            species_results: unknown[];
        };
        /** SoilExtractValuesInput */
        SoilExtractValuesInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
        };
        /** SoilExtractValuesResponse */
        SoilExtractValuesResponse: {
            /** Smr */
            smr: number;
            /** Snr */
            snr: number;
        };
        /** SoilIndicatorSpeciesResponse */
        SoilIndicatorSpeciesResponse: {
            /** Indicator Species */
            indicator_species: string[];
        };
        /** SoilMappingsResponse */
        SoilMappingsResponse: {
            /** Smr */
            SMR: components["schemas"]["MappingItem"][];
            /** Snr */
            SNR: components["schemas"]["MappingItem"][];
        };
        /** SoilTypeSurveyInput */
        SoilTypeSurveyInput: {
            /**
             * Soil Type
             * @example 1 Brown earth
             */
            soil_type: string;
        };
        /** SoilTypeSurveyResponse */
        SoilTypeSurveyResponse: {
            /** Smr */
            smr: number;
            /** Snr */
            snr: number;
        };
        /** SoilTypesResponse */
        SoilTypesResponse: {
            /** Soil Types */
            soil_types: string[];
        };
        /** SoilVegetationSurveyInput */
        SoilVegetationSurveyInput: {
            /**
             * Veg Survey
             * @example {
             *       "bramble": 25,
             *       "creeping buttercup": 15,
             *       "foxglove": 10,
             *       "hard-fern": 10,
             *       "herb robert": 30
             *     }
             */
            veg_survey: {
                [key: string]: number;
            };
        };
        /** SoilVegetationSurveyResponse */
        SoilVegetationSurveyResponse: {
            /** Smr */
            smr: number;
            /** Snr */
            snr: number;
            /** F */
            f: number;
            /** Rn */
            rn: number;
            /** Wilson */
            wilson: number;
        };
        /** SpeciesAPP4FutureResponse */
        SpeciesAPP4FutureResponse: {
            /** Speciesid */
            speciesID: number;
            /** Speciescode */
            speciesCode: string;
            /** Commonname */
            commonName: string;
            /** Scientificname */
            scientificName: string;
        };
        /** SpeciesESCV4Response */
        SpeciesESCV4Response: {
            /** Speciescode */
            speciesCode: string;
            /** Speciesname */
            speciesName: string;
            /** Speciesscientific */
            speciesScientific: string;
            /** Conifer */
            conifer: string;
            /** Native */
            native: string;
            /** Mainspecies */
            mainSpecies: string;
            /** Wanestatus */
            waneStatus: string;
            /** Agroforestry */
            agroforestry: string;
        };
        /** TopographicExtractValuesInput */
        TopographicExtractValuesInput: {
            /**
             * Loc
             * @example [
             *       400000,
             *       650000
             *     ]
             */
            loc: [
                number,
                number
            ];
        };
        /** TopographicExtractValuesResponse */
        TopographicExtractValuesResponse: {
            /** Elevation */
            elevation: number;
            /** Slope */
            slope: number;
            /** Aspect */
            aspect: number;
            /** Dams */
            dams: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_esc_v4_species_api_species_esc_v4_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Look-up for ESC V4 tree species */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "speciesCode": "AH",
                     *         "speciesName": "Ash",
                     *         "speciesScientific": "Fraxinus excelsior",
                     *         "conifer": "No",
                     *         "native": "Yes",
                     *         "mainSpecies": "No",
                     *         "waneStatus": "Exempt",
                     *         "agroforestry": "No"
                     *       },
                     *       {
                     *         "speciesCode": "AMA",
                     *         "speciesName": "Big leaf maple",
                     *         "speciesScientific": "Acer macrophylum",
                     *         "conifer": "No",
                     *         "native": "No",
                     *         "mainSpecies": "No",
                     *         "waneStatus": "Not exempt",
                     *         "agroforestry": "No"
                     *       },
                     *       {
                     *         "speciesCode": "ASP",
                     *         "speciesName": "Aspen",
                     *         "speciesScientific": "Populus tremula",
                     *         "conifer": "No",
                     *         "native": "Yes",
                     *         "mainSpecies": "Yes",
                     *         "waneStatus": "Exempt",
                     *         "agroforestry": "Yes"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["SpeciesESCV4Response"][];
                };
            };
        };
    };
    get_app4future_species_api_species_app4future_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Look-up for APP4Future tree species */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "speciesID": 1025,
                     *         "speciesCode": "ALM",
                     *         "commonName": "Almond",
                     *         "scientificName": "Prunus dulcis (Mill.) D.A.Webb"
                     *       },
                     *       {
                     *         "speciesID": 1019,
                     *         "speciesCode": "AP",
                     *         "commonName": "Apple",
                     *         "scientificName": "Malus domestica (Suckow) Borkh."
                     *       },
                     *       {
                     *         "speciesID": 1022,
                     *         "speciesCode": "APR",
                     *         "commonName": "Apricot",
                     *         "scientificName": "Prunus armeniaca L."
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["SpeciesAPP4FutureResponse"][];
                };
            };
        };
    };
    get_indicator_species_api_soil_indicator_species_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of indicator species */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "indicator_species": [
                     *         "bell heather",
                     *         "blaeberry,bilberry"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SoilIndicatorSpeciesResponse"];
                };
            };
        };
    };
    get_soil_types_api_soil_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of soil types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "soil_types": [
                     *         "1 Brown earth",
                     *         "1d Basic brown earth",
                     *         "1u Upland brown earth"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SoilTypesResponse"];
                };
            };
        };
    };
    get_soil_mapping_api_soil_mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Look-up array for SMR and SNR */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "SMR": [
                     *         {
                     *           "num": 1,
                     *           "description": "Very wet",
                     *           "code": "VW"
                     *         },
                     *         {
                     *           "num": 2,
                     *           "description": "Wet",
                     *           "code": "W"
                     *         },
                     *         {
                     *           "num": 3,
                     *           "description": "Very moist",
                     *           "code": "VM"
                     *         },
                     *         {
                     *           "num": 3.5,
                     *           "description": "Moist",
                     *           "code": "M"
                     *         },
                     *         {
                     *           "num": 4,
                     *           "description": "Moist",
                     *           "code": "M"
                     *         },
                     *         {
                     *           "num": 5,
                     *           "description": "Fresh",
                     *           "code": "F"
                     *         },
                     *         {
                     *           "num": 6,
                     *           "description": "Slightly dry",
                     *           "code": "SD"
                     *         },
                     *         {
                     *           "num": 7,
                     *           "description": "Moderately dry",
                     *           "code": "MD"
                     *         },
                     *         {
                     *           "num": 8,
                     *           "description": "Very dry",
                     *           "code": "VD"
                     *         }
                     *       ],
                     *       "SNR": [
                     *         {
                     *           "num": 0,
                     *           "description": "Very poor 1",
                     *           "code": "VP1"
                     *         },
                     *         {
                     *           "num": 0.5,
                     *           "description": "Very poor 2",
                     *           "code": "VP2"
                     *         },
                     *         {
                     *           "num": 1,
                     *           "description": "Very poor 3",
                     *           "code": "VP3"
                     *         },
                     *         {
                     *           "num": 1.5,
                     *           "description": "Very poor-Poor",
                     *           "code": "VP-P"
                     *         },
                     *         {
                     *           "num": 2,
                     *           "description": "Poor",
                     *           "code": "P"
                     *         },
                     *         {
                     *           "num": 3,
                     *           "description": "Medium",
                     *           "code": "M"
                     *         },
                     *         {
                     *           "num": 4,
                     *           "description": "Rich",
                     *           "code": "R"
                     *         },
                     *         {
                     *           "num": 5,
                     *           "description": "Very rich",
                     *           "code": "VR"
                     *         },
                     *         {
                     *           "num": 6,
                     *           "description": "Carbonate",
                     *           "code": "C"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SoilMappingsResponse"];
                };
            };
        };
    };
    vegetation_survey_api_soil_vegetation_survey_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoilVegetationSurveyInput"];
            };
        };
        responses: {
            /** @description Vegetation survey results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "smr": 4,
                     *       "snr": 4,
                     *       "f": 6.17,
                     *       "rn": 11.17,
                     *       "wilson": 4.53
                     *     }
                     */
                    "application/json": components["schemas"]["SoilVegetationSurveyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_soil_values_api_soil_extract_values_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoilExtractValuesInput"];
            };
        };
        responses: {
            /** @description Value of SMR and SNR rasters at given location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "smr": 3,
                     *       "snr": 3
                     *     }
                     */
                    "application/json": components["schemas"]["SoilExtractValuesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soil_survey_api_soil_type_survey_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoilTypeSurveyInput"];
            };
        };
        responses: {
            /** @description Soil survey results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "smr": 5,
                     *       "snr": 3
                     *     }
                     */
                    "application/json": components["schemas"]["SoilTypeSurveyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_available_climate_datasets_api_climate_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClimateDatasetsInput"];
            };
        };
        responses: {
            /** @description List of available climate datasets for specified location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "name": "Core",
                     *         "coverage": "GB",
                     *         "description": "Core ESC datasets for baseline period",
                     *         "variables": [
                     *           "at",
                     *           "md"
                     *         ]
                     *       },
                     *       {
                     *         "name": "CHESS_SCAPE_v1",
                     *         "coverage": "GB",
                     *         "description": "Climatic variables calculated using CHESS-SCAPE (UKCP18)",
                     *         "scenarios": [
                     *           "1980_2000",
                     *           "2000_2020",
                     *           "2020_2040",
                     *           "2040_2060",
                     *           "2060_2080"
                     *         ],
                     *         "rcps": [
                     *           "rcp26",
                     *           "rcp45",
                     *           "rcp60",
                     *           "rcp85"
                     *         ],
                     *         "members": [
                     *           "01",
                     *           "04",
                     *           "06",
                     *           "15"
                     *         ]
                     *       },
                     *       {
                     *         "name": "CHESS_SCAPE_v2",
                     *         "coverage": "GB",
                     *         "description": "Climatic variables calculated using CHESS-SCAPE UKCP18 (2024). Includes additional climate parameters to CHESS_SCAPE_v1. Does not include md (moisture deficit).",
                     *         "variables": [
                     *           "at",
                     *           "pr",
                     *           "pr_summer",
                     *           "pr_winter",
                     *           "wq_aridity"
                     *         ],
                     *         "scenarios": [
                     *           "1980_2000",
                     *           "2000_2020",
                     *           "2020_2040",
                     *           "2040_2060",
                     *           "2060_2080"
                     *         ],
                     *         "rcps": [
                     *           "rcp26",
                     *           "rcp85"
                     *         ],
                     *         "members": [
                     *           "01"
                     *         ]
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["ClimateDatasetsResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_climate_values_api_climate_extract_values_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClimateExtractValuesInput"];
            };
        };
        responses: {
            /** @description Climate values for multiple climate scenarios at specified location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "inputs": {
                     *         "loc": [
                     *           400000,
                     *           650000
                     *         ],
                     *         "climate_dataset": "CHESS_SCAPE_v1",
                     *         "variables": [
                     *           "at"
                     *         ],
                     *         "period_list": [
                     *           "1980_2000",
                     *           "2040_2060",
                     *           "2060_2080"
                     *         ],
                     *         "rcp_list": [
                     *           "baseline",
                     *           "rcp26",
                     *           "rcp85"
                     *         ]
                     *       },
                     *       "results": {
                     *         "1980_2000": {
                     *           "baseline": {
                     *             "at": 1395.13
                     *           }
                     *         },
                     *         "2040_2060": {
                     *           "rcp26": {
                     *             "at": 1957.77
                     *           }
                     *         },
                     *         "2060_2080": {
                     *           "rcp85": {
                     *             "at": 2436.11
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ClimateExtractValuesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_topographic_values_api_topographic_extract_values_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopographicExtractValuesInput"];
            };
        };
        responses: {
            /** @description Topographic values at specified location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "elevation": 123,
                     *       "slope": 5,
                     *       "aspect": 75,
                     *       "dams": 12
                     *     }
                     */
                    "application/json": components["schemas"]["TopographicExtractValuesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_esc_v4_options_api_models_esc_v4_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Options for ESC V4 model run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "species_filters": {
                     *         "filterWANE": [
                     *           "None",
                     *           "Exempt",
                     *           "Not exempt"
                     *         ],
                     *         "filterConifer": [
                     *           "None",
                     *           "Conifer",
                     *           "Broadleaf"
                     *         ],
                     *         "filterNative": [
                     *           "None",
                     *           "Yes",
                     *           "No"
                     *         ],
                     *         "filterMain": [
                     *           "None",
                     *           "Yes",
                     *           "No"
                     *         ],
                     *         "filterAgro": [
                     *           "None",
                     *           "Yes",
                     *           "No"
                     *         ]
                     *       },
                     *       "site_management": {
                     *         "brash": [
                     *           "None (new planting)",
                     *           "Fresh brash < 18 months",
                     *           "Brash > 18 months"
                     *         ],
                     *         "drainage": [
                     *           "None",
                     *           "Drainage installed"
                     *         ],
                     *         "fertiliser": [
                     *           "None",
                     *           "Fertiliser",
                     *           "Nursing mix"
                     *         ]
                     *       },
                     *       "site_modification": {
                     *         "exposure": [
                     *           "None",
                     *           "Exposed ridge/Coastal zone",
                     *           "Local shelter/Less exposed/Underplanting"
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ModelsESCV4OptionsResponse"];
                };
            };
        };
    };
    run_stand_model_api_models_esc_v4_stand_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ESCV4RunInput"];
            };
        };
        responses: {
            /** @description ESC V4 model response for multiple climate scenarios for given location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "inputs": {
                     *         "loc": [
                     *           438000,
                     *           203000
                     *         ],
                     *         "climate_dataset": "CHESS_SCAPE_v1",
                     *         "period_list": [
                     *           "1980_2000",
                     *           "2060_2080"
                     *         ],
                     *         "rcp_list": [
                     *           "baseline",
                     *           "rcp85"
                     *         ],
                     *         "smr": 3,
                     *         "snr": 3,
                     *         "smr_source": "Manual entry",
                     *         "snr_source": "Manual entry",
                     *         "filterWANE": "None",
                     *         "filterConifer": "None",
                     *         "filterNative": "None",
                     *         "filterMain": "No",
                     *         "filterAgro": "Yes",
                     *         "brash": "None (new planting)",
                     *         "drainage": "None",
                     *         "fertiliser": "None",
                     *         "exposure": "None"
                     *       },
                     *       "results": {
                     *         "BPO": {
                     *           "1980_2000": {
                     *             "baseline": {
                     *               "atF": 1,
                     *               "ctF": 1,
                     *               "smrF": 1,
                     *               "snrF": 0.6,
                     *               "daF": 0.95,
                     *               "mdF": 1,
                     *               "min_response": 0.6,
                     *               "suit": 0.6,
                     *               "yc": 10,
                     *               "lim_fac": "snr"
                     *             }
                     *           },
                     *           "2060_2080": {
                     *             "rcp85": {
                     *               "atF": 0.26,
                     *               "ctF": 1,
                     *               "smrF": 1,
                     *               "snrF": 0.6,
                     *               "daF": 0.95,
                     *               "mdF": 0,
                     *               "min_response": 0,
                     *               "suit": 0,
                     *               "yc": 0,
                     *               "lim_fac": "md"
                     *             }
                     *           }
                     *         },
                     *         "CAR": {
                     *           "1980_2000": {
                     *             "baseline": {
                     *               "atF": 1,
                     *               "ctF": 1,
                     *               "smrF": 1,
                     *               "snrF": 0.86,
                     *               "daF": 0.82,
                     *               "mdF": 1,
                     *               "min_response": 0.82,
                     *               "suit": 0.82,
                     *               "yc": 10,
                     *               "lim_fac": "dams"
                     *             }
                     *           },
                     *           "2060_2080": {
                     *             "rcp85": {
                     *               "atF": 0.47,
                     *               "ctF": 1,
                     *               "smrF": 1,
                     *               "snrF": 0.86,
                     *               "daF": 0.82,
                     *               "mdF": 0,
                     *               "min_response": 0,
                     *               "suit": 0,
                     *               "yc": 0,
                     *               "lim_fac": "md"
                     *             }
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ESCV4RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stand_model_agro_api_models_app4future_stand_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APP4FutureInput"];
            };
        };
        responses: {
            /** @description Response for APP4Future ESC model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "inputs": {
                     *         "loc": [
                     *           438000,
                     *           203000
                     *         ],
                     *         "climate_dataset": "CHESS_SCAPE_v2",
                     *         "period_list": [
                     *           "1980_2000",
                     *           "2060_2080"
                     *         ],
                     *         "rcp_list": [
                     *           "baseline",
                     *           "rcp85"
                     *         ]
                     *       },
                     *       "results": {
                     *         "IAR": {
                     *           "1980_2000": {
                     *             "baseline": {
                     *               "prF": 1,
                     *               "atF": 1,
                     *               "wq_aridityF": 1,
                     *               "smrF": 0.93,
                     *               "snrF": 0.61,
                     *               "daF": 0.91
                     *             }
                     *           },
                     *           "2060_2080": {
                     *             "rcp85": {
                     *               "prF": 0,
                     *               "atF": 1,
                     *               "wq_aridityF": 0,
                     *               "smrF": 0.93,
                     *               "snrF": 0.61,
                     *               "daF": 0.91
                     *             }
                     *           }
                     *         },
                     *         "CAR": {
                     *           "1980_2000": {
                     *             "baseline": {
                     *               "prF": 1,
                     *               "atF": 1,
                     *               "wq_aridityF": 1,
                     *               "smrF": 1,
                     *               "snrF": 0.36,
                     *               "daF": 0.82
                     *             }
                     *           },
                     *           "2060_2080": {
                     *             "rcp85": {
                     *               "prF": 1,
                     *               "atF": 1,
                     *               "wq_aridityF": 0,
                     *               "smrF": 1,
                     *               "snrF": 0.36,
                     *               "daF": 0.82
                     *             }
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APP4FutureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_nvc_model_api_models_nvc_v4_stand_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NVCInput"];
            };
        };
        responses: {
            /** @description PLACEHOLDER - ENDPOINT IN DEVELOPMENT - DO NOT USE: Runs NVC model for given location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "W1": {
                     *         "1980_2000": {
                     *           "baseline": {
                     *             "atF": 1,
                     *             "ctF": 1,
                     *             "smrF": 0,
                     *             "snrF": 0.71,
                     *             "daF": 0.67,
                     *             "mdF": 0.79,
                     *             "min_response": 0,
                     *             "suit": 0,
                     *             "lim_fac": "smr"
                     *           }
                     *         }
                     *       },
                     *       "W2": {
                     *         "1980_2000": {
                     *           "baseline": {
                     *             "atF": 1,
                     *             "ctF": 1,
                     *             "smrF": 0.65,
                     *             "snrF": 0.84,
                     *             "daF": 0.86,
                     *             "mdF": 0.87,
                     *             "min_response": 0.65,
                     *             "suit": 0.65,
                     *             "lim_fac": "smr"
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["NVCV4Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_fdt_model_api_models_fdt_v4_stand_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FDTV4Input"];
            };
        };
        responses: {
            /** @description PLACEHOLDER - ENDPOINT IN DEVELOPMENT - DO NOT USE - Runs Forest Development Type (FDT) model for multiple climate scenarios for given location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "1980_2000": {
                     *         "baseline": {
                     *           "Sitka spruce even aged": {
                     *             "prim_spec": "SS",
                     *             "prim_spec_perc": "90-100",
                     *             "even-aged_Unthinned": "x",
                     *             "even-aged_Thinned": "x*",
                     *             "at_suit": 1,
                     *             "md_suit": 1,
                     *             "dams_suit": 1,
                     *             "smr_suit": 1,
                     *             "snr_suit": 1,
                     *             "all_suit": 1
                     *           },
                     *           "Sitka spruce uneven aged": {
                     *             "prim_spec": "SS",
                     *             "prim_spec_perc": "80-90",
                     *             "uneven-aged_Simple": "x*",
                     *             "uneven-aged_Complex": "x",
                     *             "at_suit": 1,
                     *             "md_suit": 1,
                     *             "dams_suit": 1,
                     *             "smr_suit": 1,
                     *             "snr_suit": 1,
                     *             "all_suit": 1
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": {
                        [key: string]: {
                            [key: string]: {
                                [key: string]: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_model_api_models_hmss_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HMSSModelInput"];
            };
        };
        responses: {
            /** @description HMSS model results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_glossary_api_content_results_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Glossary for result table */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "site_information": [
                     *         {
                     *           "abbreviation": "AT",
                     *           "term": "Accumulated temperature (degree-days >5 °C)",
                     *           "description": "Measure of climatic warmth. Calculated by summing daily temperatures above 5°C over a year (degree‑days). A site is considered warm if it has an accumulated temperature greater than 1200°C."
                     *         },
                     *         {
                     *           "abbreviation": "MD",
                     *           "term": "Moisture deficit (mm)",
                     *           "description": "Measure of climatic wetness. Calculated from the difference between potential evapotranspiration and precipitation. A site is considered wet if it has a moisture deficit less than 90 mm and moderately dry if it has a moisture deficit greater than 260mm. Moisture deficit is a measure of climate only and is not influenced by water holding capacity of the soil or topographic effects."
                     *         },
                     *         {
                     *           "abbreviation": "CT",
                     *           "term": "Continentality (Conrad index)",
                     *           "description": "Measure of how strongly climate is influenced by distance from the sea and latitude. Ranges from 1 (oceanic, with mild seasonal variation) to 12 (continental, with stronger seasonal variation in temperature and precipitation)."
                     *         }
                     *       ],
                     *       "species_results": [
                     *         {
                     *           "term": "RCP",
                     *           "definition": "Representative Concentration Pathways. The climate projection scenario defined by radiative forcing levels (e.g. 2.6 W m-2). RCP2.6 represents a best-case, low emissions scenario. RCP8.5 represent a worst-case, high emissions scenario. For more information, see Met Office guidance."
                     *         },
                     *         {
                     *           "term": "Period",
                     *           "definition": "The time period of the climate projection. Results are calculated using the average projected climate conditions for that period under a given RCP. Currently, 1980–2000 represents the ‘baseline’ climate."
                     *         },
                     *         {
                     *           "term": "Suitability score for site parameters",
                     *           "definition": "Measure of species suitability for individual site parameters. Scores range from 0 to 1, with 0-0.3 considered unsuitable, 0.3-0.5 marginal, 0.5-0.75 suitable and >= 0.75 (very suitable). "
                     *         },
                     *         {
                     *           "term": "AT",
                     *           "definition": "Accumulated temperature, a measure of climatic warmth. Calculated by summing daily temperatures above 5°C over a year."
                     *         },
                     *         {
                     *           "term": "MD",
                     *           "definition": "Moisture deficit, a measure of climatic wetness. Calculated from the difference between potential evapotranspiration and precipitation."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ResultsGlossary"];
                };
            };
        };
    };
}
